default: &default
  smtp:
    username:
    password:
    address: localhost
    domain: example.com
    port: 25

  imipre:
    domain: IMIPRE
    scope: IMI_BASIC_PRE.Info
    site: https://appspre.ajuntament.bcn
    redirect_uri: https://aytobarcelona-decidim.dev.aspgems.com/users/auth/imipre/callback

  geocoder_lookup_app_id: <%= ENV["HERE_APP_ID"] %>
  geocoder_lookup_app_code: <%= ENV["HERE_APP_CODE"] %>

  saml:
    idp_sso_target_url: <%= ENV['IDP_SSO_TARGET_URL'] %>
    idp_cert: <%= ENV['IDP_CERT'] %>
    certificate: <%= ENV['CERTIFICATE'] %>
    private_key: <%= ENV['PRIVATE_KEY'] %>
    sp_entity_id: <%= ENV['SP_ENTITY_ID'] %>
    user_types: ['T1', 'T2', 'T3', 'T11']

development:
  <<: *default
  secret_key_base: 4de720903a5d5f54094210f69423493dfdc56413a42907f7684766bff965695c0deec064fc03eff5c1e34fff618f70bdcac7127d853d6a0e5a4c48ccc267f2ad
test:
  <<: *default
  secret_key_base: 8d0e722712908c69c5005aefe275472ba3eae7fe30f982155dcd816896155f7e3848223af932c530de9baf0f22af45a9f15e64a7af315f99d0a5bb1e48c1e332
production:
  <<: *default
  _secure_secret_key_base: fs55LjONItwaJFJIPG8hgHBl1uUNxb5TPRUk1WJOLiBnisNFuE9GGSyUs7gdt3531ndG5NICeFPyb4sPV60PEAvTzhTFaT08qeYcr6JcbLXJakNhh9sMLqd9wDM7Kzwv5Or3DHeCa/k7y4gS61jeK3ewhbE25Sy6OmJqSIR3cdNlYMLN4U4WawWRkrmXkpk5Qf4J4OtujgXxlk3Kd57HcJuwg/E/bdP2XnYDWmA6XnZlwDQ9arvIqI2prI53ypsWpg3GRn2kzL2a1ZDKayCADbRnfoHPaukkQKxDBIiR20SF8ID7joaZrMqb3kKA5umYGtPtSBcQKvFvVeligbDyeg==#g/4pyruAcaAU5B2I4y5Ghg==#gTCfJRl7xiYqKHDkVceFpr2nyGkMZZtolr93RToV9j5B19XNq/SZ5rrnMR3aub+LZlFONkTyk9XIZKGFaAgydgjuX/diOZVcTdkyyWGZz9uTOnaT5hHm9K2+2ab1rQ3dEPhHJCiA4RcKtUM3zlO/D2KT1Z4PcmvzSy6SG0CKlQ2guHmNz3HoAeUY4cIH0lXG
  imipre:
    _secure_client_id: QJ++QBy+UHPeCf3lduM2OBCBqLjo8vNyEBi55Azci+QcaMo2ZmyHFqV52p/igrCjMp1ssLPYZ8flZRS8R9qaA2/Z6PywbZMlU+HLasmNR5HPw57FDezAfpFQs3U5H+uIWIHA5DNMTiDgmvdBqGRT6wja/alTbiAl/Mt84V+CYlsloHP3kbaug5Agnb2z+RJaTnm0OOSl6L7aVeQMJQgVgD7roVU5nCkHoYmV1/llrcwBbtYahQNLbmm7pJiyMnZG9Ep4kM6REOIOkKCTOFP2nTTVzO6sxxtsXysxgFePl4Ijl1wta4Y2lXImWlzBATU7w5rqdRxe8eyf/18gGgPLOg==
    _secure_client_secret: BImiX6USuZK/G7AM6iMM8na6r0bV2mpoT/KmhR+paV0v51NGYsWsAgqkADgKFpSMLuipv+Z290otzMPlREvQChs2f3mEJktAoi50bVBfv0P7Z+aRdTO8K2q6xJiBIwxwzJIw7s8L3CALWHPXhVxYR3xDEeKiv10jW8hOqT7c/bReN5DQ+5sw8GJPg8RQa0IlCjqZXZ2mtN49AjJ+aTSShbSlxD60Pa5nwEe8ZdLKJg+gqLfDPNpn6neKIp/LIKpZmEUUN9sHuONOK76nKB2GGSkTK3oS16OzJgOqxp+8rfhAJQu/fKEN6jIqyek0iETdOPEaPbfgXD+Kz0MGm/LyxA==
    domain: IMIPRE
    scope: IMI_BASIC_PRE.Info
    site: https://appspre.ajuntament.bcn
    redirect_uri: https://aytobarcelona-decidim.dev.aspgems.com/users/auth/barcelona-rrhh/callback
    info_url: https://appspre.ajuntament.bcn/oauth2/rest/token/info?access_token=
